### PR TITLE
Added support for LambdaTest selenium grid

### PR DESCRIPTION
**Pull request by nikhil-lambda**
**This pull request is about adding support for LambdaTest selenium grid 🚀**

### Description
LambdaTest provides a distributed selenium grid which helps you to perform testing 4+ windows platform, 6+ Expensive mac platforms and a wide range of browsers. 

### Motivation and Context
- Zalenium should try to support as many third-party services as possible in order to give users a choice. 
- We have received a few requests from our valuable customers to run a test using zalenium.
- Based on customer demand.  @nextlevelbeard! has raised an issue #947 

### How Has This Been Tested?
- We have designed our code such a manner it should not affect other areas of code. and after testing, we found that it is working in the desired manner 
- we ran the test on zalenium dockerize browsers and verified dashboard.
- we ran all test on cloud grid provider i.e. LambdaTest using zalenium and Verified Zalenium & LambdaTest Dashboard and Logs.
- we ran the test on zalenium dockerize browsers which are available and pass the rest tests to cloud grid provider i.e. LambdaTest Verified Zalenium & LambdaTest Dashboard and Logs.
- We have performed extensive testing of the above-mentioned use cases on Linux, Windows, and Mac machines.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Hi, @diemol @elgalu  will be needing yours 👍 to our pull request. We appreciate the idea of Zalenium which make the testing faster and hassle-free.  and this pull request is raised to help customer likes 
@nextlevelbeard  which already opened an issue at zalenium #947

### CODE REVIEW

**Comment by diemol** [comment]
Hi @nikhil-lambda, thank you very much for this PR!

How can I get an open source account for LambdaTest so I can add it to the integration tests we have on Travis? Also to check the basic functionality.

**Comment by nikhil-lambda** [comment]
Hi @diemol, Thanks for reviewing the PR!. Can you please sign up on our platform? and let me know, We will process your open source account in no time. [Sign up here](https://accounts.lambdatest.com/register) :point_left:. I appreciate your help, TIA.

**Comment by diemol** [comment]
Hi @nikhil-lambda, thanks for your quick reply!
I just signed up under my gmail address, which has the same handle as my GitHub username (@diemol).
I'll start checking more in detail in a couple of weeks since I am on holiday right now.

**Comment by nikhil-lambda** [comment]
Hi @diemol, Thanks for signing up with us.  We have processed your account.  You can now perform testing on LambdaTest platform. Good luck for the holidays👍.  

Note: Your account is on  2 concurrent sessions.  Valid till 9th September 2019

**Comment by diemol** [comment]
@nikhil-lambda is it possible to have it for at least 1 year and renew it? Or indefinitely? 
The accounts we have with Sauce Labs, TestingBot, CrossBrowserTesting and BrowserStack work in the same way. The reason for this is because every PR runs tests against each cloud service to make sure the integration is still working.

**Comment by 4DvAnCeBoY** [comment]
@diemol We have upgraded your account validity till 31st December 2022 on 2 parallel session plan.

**Comment by diemol** [comment]
Merging to a protected branch so we can run all tests through Travis.

**Comment by diemol** [comment]
Thanks @nikhil-lambda!
I just checked it, all seems to be working as expected :)
I'll merge #1011 and release.

**Pull request merged**
