### PR TITLE
Move starter proxy responsibilities into proxy set. 

### PR DESCRIPTION
**Pull request by diemol**
Comes from #527

### CODE REVIEW

**Comment by diemol** [comment]
OK, so now Travis is passing!
We need to check the unit tests and see what has to be enabled again.

**Comment by diemol** [comment]
@dspasojevic I think the email account you used for the commits is not associated to your GitHub account, so the commits are not being associated to your GitHub user.

**Comment by dspasojevic** [comment]
Thanks for the heads up @diemol. I've linked my work accounts. It looks like the commits are correctly associated now.

**Comment by peerster** [comment]
@diemol Anything left to test or change now? Very excited about getting this merged and to get a new release of zalenium 😸

**Comment by diemol** [comment]
@peerster the thing is that some unit tests are failing now, and even if the integration tests are passing, I'd  like to review the unit tests first :)
I'll try to check them during this week, but any help is appreciated. After that, I think we can be more confident to release.

**Comment by dspasojevic** [comment]
Thanks for looking @pearj. I added a `SimpleRegistry` that requires a bit less mocking for the other tests. I think that if I change that test to use it, it should pass. I'll give it a go.

**Comment by pearj** [comment]
👍

**Comment by diemol** [comment]
👍

**Comment by pearj** [comment]
👍

**Pull request merged**
