### PR TITLE
Documentation improvement: video + docker-compose

### PR DESCRIPTION
**Pull request by AronNovak**
About `--abort-on-container-exit`

### CODE REVIEW

**Comment by elgalu** [comment]
Thanks for the PR @AronNovak and for pointing out this problem.

Between yesterday and today we improved Zalenium so it waits for the video files to exist (while stopping) precisely to avoid this problem.

Can you pull latest and try again? we would love to see if this is solved and the documentation changes are no longer necessary.

**Comment by AronNovak** [comment]
Just tried it out now, as you can see on this Jenkins log: https://travis-ci.org/Gizra/drupal-elm-starter/jobs/219702104
I have the `start-video`, but not the `stop-video` counterpart.

**Comment by elgalu** [comment]
Not sure if related but I see in the log:

> test_server.sh: line 32: [: missing `]'

**Comment by AronNovak** [comment]
@elgalu It's unrelated, we altered the condition to go always on the failing part, to test the video upload, it emits this warning but it just attempts to upload the video correctly.

**Comment by diemol** [comment]
We'll check it on Monday, and after testing the command, I think we will merge.

**Comment by elgalu** [comment]
:+1:

**Comment by diemol** [comment]
👍

**Pull request merged**
