### PR TITLE
First cut of kubernetes support #103

### PR DESCRIPTION
**Pull request by pearj**
What works now:

* Creating containers
* Deleting containers
* Live preview
* Exec commands
* Copying files
* Mounting the shared volume

What is missing:
* Documentation

### CODE REVIEW

**Comment by diemol** [comment]
Hi @pearj,

Thanks for the PR!

We will merge it after we release the changes we are doing for performance, hopefully end of this week.

On the mean time, is it possible for you to add a markdown file with some setup instructions?

**Comment by pearj** [comment]
Sure, I'll add some doco. 

Hopefully by the end of the week I'll have solved file copying. Fingers crossed tomorrow.

**Comment by pearj** [comment]
I got copying files working. Turns out I had the tar command syntax wrong, whoops!  Also I ran into bugs with kubernetes-client how it handles streams being shutdown in failure scenarios.

But I have it working now, yay.

Tomorrow I think I'll add a flag "--minSpareCapacity" or something.  Because the time to start a node in kubernetes is pretty slow, so kubernetes will need something like that.

I'll write some doco tomorrow too

**Comment by pearj** [comment]
I've now added support for auto-mounting the shared drive across all the nodes.

I've started on the Doco, but because we use OpenShift here I'm using some features to start zalenium that are OpenShift specific, so I'll have to find out what works in Kubernetes.

The kubernetes support inside Zalenium itself is only using the kubernetes api at the moment, so that's safe. It's just starting the zalenium server itself, I'll have to find find some examples that work in native kubernetes.

**Comment by MiluchOK** [comment]
If you tell me how to use it, I'll sell you my soul and all my belongings!

**Comment by diemol** [comment]
Hi @pearj, we just released 3.3.1i, which is the work we did during the last two weeks. 
I'll review this PR quickly tomorrow and I'll merge it to the new branch I created, so after that we can start trying it here. I guess that Minikube will do for the initial testing.

Again, thanks a lot for the effort you have put on this!

**Comment by pearj** [comment]
Lol @MiluchOK.  I promise I'll write some doco today.

**Comment by pearj** [comment]
Sooo, I don't think doco will come till next week :(.  My workstation, which is a virtual machine, has died and being Friday afternoon here all the people that can fix have gone for the long weekend.  So it will have to wait until Tuesday.

I have fixed a few other bugs, but I can't commit them because they're still on that workstation.

I also made it possible to override the selenium image, which is normally "elgalu/selenium".  I found that it's pretty slow if it has to check with docker hub ever time a node starts, especially from Australia at least. It adds about 5 extra seconds to the start time when there is no update.  I found that specifying a private registry is a lot faster, plus it means you can control when your selenium nodes should update.

Since I use OpenShift, I did a little bit of research about what is available with plain kubectl, and it looks like you can get most of it done with something like `kubectl run zalenium-test --image=172.23.192.79:5000/delivery/zalenium --env="http_proxy=" --env="https_proxy=" --env="HTTP_PROXY=" --env="HTTPS_PROXY=" --overrides='{"spec": {"template": {"spec": {"serviceAccount": "zalenium"}}}}' -l app=zalenium-test --port=4444 -- start --firefoxContainers 0 --chromeContainers 2`

That only exposes port 4444 though, so either it will need a yaml file or an kubectl patch, to add port 5555 as well.

**Comment by diemol** [comment]
👍

**Comment by elgalu** [comment]
👍

**Comment by pearj** [comment]
Thanks!

**Comment by diemol** [comment]
Thanks for your effort @pearj!
We'll play with during this week, and help with all the TODOs.

**Comment by diemol** [comment]
I pushed one commit to the kubernetes brach to fix a little thing with the containerId method, which didn't let the the whole video recording etc... work. 

The first thing I was doing was just to check that Zalenium in docker was still working, and it looks that it works well 👍 

Now we can actually focus on checking it in kubernetes during this week, looking forward to that!

**Pull request merged**
