### PR TITLE
Add tolerations field

### PR DESCRIPTION
**Pull request by dkder3k**
### Description
Add toleration field to pod configuration to be able to use zalenium on nodes with taints.

### Motivation and Context
At the moment selenium nodes that are created after start of zalenium always stuck in pending status - they can't start on tainted nodes ([issue](https://github.com/zalando/zalenium/issues/745))

### How Has This Been Tested?
I tested this feature on k8s cluster v1.12.1 with 1 master and 2 nodes.
One of nodes had taints. I deployed zalenium with 2 desired selenium containers and configured tolerations. All works as expected.
After I've removed tolerations I redeployed zalenium and check that without taints and tolerations all works fine.

### Types of changes

- [x] New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
Hi @dkder3k, thanks for the PR!

@pearj, any comments?

**Comment by dkder3k** [comment]
Hi @diemol 
Today I'm going to extend [helm chart in docs](https://github.com/zalando/zalenium/tree/master/docs/k8s/helm) with actual info
Also I try to write some tests to avoid code coverage reduction

**Comment by diemol** [comment]
Hi @dkder3k, sure, go for it!

**Comment by diemol** [comment]
Thanks @dkder3k!

**Pull request merged**
