### PR TITLE
Fixed grep for container id when running in DinD

### PR DESCRIPTION
**Pull request by mattcfox**
The way that the container id was previous found was broken when using zalenium with Docker in Docker, and would retrieve the DinD container's id.

### CODE REVIEW

**Comment by diemol** [comment]
Hi @mattcfox, thanks for this PR.

Just want to double check if I understood, you are running Zalenium inside a docker container, and all the other docker-selenium containers are created inside that initial container?

**Comment by elgalu** [comment]
:+1:

**Comment by diemol** [comment]
👍

**Comment by elgalu** [comment]
:+1:

**Comment by diemol** [comment]
Thanks for the PR @mattcfox, we tested it and it works well :)

**Comment by mattcfox** [comment]
@diemol, apologies for the late reply.  Yes, I'm running zalenium as well as all of the containers it spawns within a single container.  I'm using `docker:stable-dind`.

**Pull request merged**
