### PR TITLE
Append testStatus to video fileName

### PR DESCRIPTION
**Pull request by kendalsickels-wf**
**Thanks for contributing to Zalenium! Please give us as much information as possible to merge this PR
quickly.**

### Description

Added testStatus to the end of the TEST_FILE_NAME_TEMPLATE and added in the replace for it within buildVideoFileName()

### Motivation and Context

While saving only the failed videos is nice I wanted to keep all videos but needed a way to easily separate the failed from successful.  By adding the testStatus to the end of the videoFileName I can easily move files to appropriate directories after Zalenium has copied them over.

### How Has This Been Tested?

Tested by building the modified version of Zalenium locally and creating a docker image. Then used that image inside our local testing platform and ran a test that would pass and a test that would fail.
Failure Log from that test:
```
36mzalenium-functional-tests_zalenium   |[0m 20:11:39.001 [Terminate Test Session int id: 
[79cedc5a-8e70-44d5-8826-18b9273b3031] ext id: [daceca3e8e8367a71a7a66fb65c424e6] 
container: [d9773f256dd3ddc3b6c5eb7a05d7fe662b8de671f4c6fa6674a7742ca83a993c]] INFO  
d.z.e.z.p.DockerSeleniumRemoteProxy - 
d9773f256dd3ddc3b6c5eb7a05d7fe662b8de671f4c6fa6674a7742ca83a993c Video file copied to: 
/home/seluser/videos/zalenium_Doc:_export_test.dart_-
_create_document_and_export_:_linuxChrome_chrome_LINUX_20180510201138496_FAILED.mp4
```

Successful Log:
```
[36mzalenium-functional-tests_zalenium   |[0m 20:10:19.525 [Terminate Test Session int id: 
[f4fdd21c-f4cc-467b-b4d9-bd8a4799658a] ext id: [f97525e3b78dea28c46e6479babb1ddd] 
container: [3fecf4b845d410702467918538cd4291c4b64887767baba8812a5d3c551021ba]] INFO  
d.z.e.z.p.DockerSeleniumRemoteProxy - 
3fecf4b845d410702467918538cd4291c4b64887767baba8812a5d3c551021ba Video file copied to: 
/home/seluser/videos/zalenium_XBRL-Module:_Test_Setup_-
_Create_Library_chrome_LINUX_20180510201019267_COMPLETED.mp4

```

### Types of changes
- [x] New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [x] All new and existing tests passed.

@diemol @pearj for review

### CODE REVIEW

**Comment by pearj** [comment]
👍

**Comment by diemol** [comment]
👍

**Comment by diemol** [comment]
Somehow the Zappr stuff is stuck, I'll merge to a different branch and then to master.

Thanks @kendalsickels-wf!

**Comment by pearj** [comment]
@diemol I edited the main description of the pr to remove a bunch of the unnecessary checkboxes. Maybe that confused it?

**Comment by diemol** [comment]
I usually do the same and it works. Maybe Zappr was down for a moment, and it is a known issue that it cannot recover the status after that. Only solution is to reopen the PR (as far as I know).

**Pull request merged**
