### PR TITLE
Ability to customize nginx client_max_body_size

### LINKED ISSUE #996: Ability to customize nginx client_max_body_size
## 🚀 Feature Proposal

As a user, i want to customize the nginx client_max_body_size setting.

## Motivation

At the moment, this value is hard coded to 300M.
If selenium driver try to upload a file bigger than this limit it will fail.

## Example

When using org.openqa.selenium.remote.LocalFileDetector, if a file path is detected, then the RemoteWebDriver will try to upload the file on the target host.
In my case, the file is bigger than this limit and the test fails, because the file upload is not possible.
In fact, zalenium grid returns a "HTTP 413 Request entity too large" response.

### PR DESCRIPTION
**Pull request by lcharlois-neotys**
At the moment, this value is hard coded to 300M.
If selenium driver try to upload a file bigger than this limit it will fail.
Fix #996

**Thanks for contributing to Zalenium! Please give us as much information as possible to merge this PR
quickly.**

Ability to customize nginx client_max_body_size

### Description
* Use parameter {{nginxMaxBodySize}} for client_max_body_size value in nginx.conf
* Add .Values.ingress.maxBodySize parameter in helm template to set NGINX_MAX_BODY_SIZE environment variable.
* Modify nginx.conf using this environment variable in zalenium.sh
* Update environment variables documentation in2000-01-05-docker.md

### How Has This Been Tested?

Not tested, because i didn't know how to test it easily.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by arnaud-deprez** [comment]
Hi @lcharlois-neotys,

Thanks for your PR.
Can I kindly ask you to squash your commits ?

Except that, the PR looks good to me and @diemol will merge it when he is back.

**Comment by lcharlois-neotys** [comment]
Hi @arnaud-deprez 

Thank you for reviewing my PR.
I've just squashed the commits.

Regards,

**Comment by diemol** [comment]
Thanks for checking in @arnaud-deprez!

@lcharlois-neotys, thank you for your PR, it looks good and we'll proceed to merge it. Just one small warning, when a test uploads a big file to the Grid, this normally uses quite some heap memory in the process, so just be aware that during that process, the memory comsumption will go up and this is something that Zalenium does not have control, it might be a bug in Grid itself.

**Comment by lcharlois-neotys** [comment]
@diemol Thanks you for accepting my PR.
And thank you for the warning also, we will monitor that point.

Regrads,

**Pull request merged**
