### PR TITLE
Allow parameters to be set via environment variables.

### PR DESCRIPTION
**Pull request by pearj**
This is especially useful for OpenShift where the UI easily allows you
to edit environment variables, but command arguments are more fiddly to
deal with.

### CODE REVIEW

**Comment by diemol** [comment]
Thanks @pearj!
This makes sense, we only have the command line parameters because the first version was just an executable. Hopefully in the future we can only have env vars.

**Comment by elgalu** [comment]
:+1:

**Comment by diemol** [comment]
👍

**Pull request merged**
