### PR TITLE
Add initial Prometheus Support

### PR DESCRIPTION
**Pull request by pearj**
### Description
Add a Prometheus `/metrics` endpoint to allow monitoring of the zalenium server, initially the JVM and Jetty metrics.  In the future, we would add specific zalenium metrics.  This lays down the initial foundation.

To enable Prometheus to work, it needed to be integrated into the Jetty server, so AspectJ has been used to access the necessary classes.

Registration of the zalenium specific servlets has been moved into Aspect, so that we get greater control of the URLs that we can use.

I also fixed a bug where the cleanup servlet would crash if it tried to delete files/directories that didn't exist.

Additionally, the Nginx redirect problem has been fixed.

### Motivation and Context
This allows us to get greater insight into the performance of zalenium and how it uses resources.  Prometheus has become the defacto standard for monitoring kubernetes clusters, so it makes to most sense to use it.

### How Has This Been Tested?
I ran few multi-threaded selenium tests and checked the `/metrics` endpoint. I also tested the existing zalenium servlets to ensure they still operated.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by pearj** [comment]
+1

**Comment by pearj** [comment]
👍

**Comment by peerster** [comment]
So this should resolve #353

**Comment by peerster** [comment]
👍

**Comment by diemol** [comment]
Cool, thanks @pearj!

What do you think? Should we merge this before #527 or after?

**Comment by diemol** [comment]
Maybe before since the other one is way bigger?

**Comment by pearj** [comment]
Merge this before. I originally raised it as a pull request to @dspasojevic’s fork. But he suggested I create it as a separate request because it’s easier to merge.

**Comment by diemol** [comment]
Sounds good, I'll merge it to a protected branch to run the complete CI.

Thanks again!

**Pull request merged**
