### PR TITLE
Fix for #276 to get containerId on Fedora

### PR DESCRIPTION
**Pull request by jkandasa**
Read #276 for more details

### CODE REVIEW

**Comment by jkandasa** [comment]
I noticed later that, this change introduced on https://github.com/zalando/zalenium/pull/113
Updated the PR to work in any environment.

**Comment by elgalu** [comment]
Looks like it doesn't work (broken in Travis) with `docker run ... -u 10006:10006` in OpenShift.

**Comment by diemol** [comment]
It fails because it cannot run the tests on BrowserStack, since the env vars are not present. Does not seem related to the PR.

**Comment by jkandasa** [comment]
Yes, looks like problem is here, 
```log
[[1;31mERROR[m] [1;31mTests [0;1mrun: [0;1m15[m, [1;31mFailures: [0;1;31m5[m, Errors: 0, [1;33mSkipped: [0;1;33m10[m, Time elapsed: 610.184 s[1;31m <<< FAILURE![m - in de.zalando.ep.zalenium.it.[1mParallelIT[m
[[1;31mERROR[m] startWebDriverAndGetBaseUrl(de.zalando.ep.zalenium.it.ParallelIT)  Time elapsed: 1.676 s  <<< FAILURE!
org.openqa.selenium.WebDriverException: 
Error forwarding the new session cannot find : Capabilities [{name=loadGooglePageAndCheckTitle, browserName=safari, platformName=MAC, platform=MAC}]
Command duration or timeout: 161 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'testing-gce-64071f0d-67a6-4288-8541-979ec13942e3', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-93-generic', java.version: '1.8.0_144'
Driver info: driver.version: RemoteWebDriver
	at de.zalando.ep.zalenium.it.ParallelIT.startWebDriverAndGetBaseUrl(ParallelIT.java:93)
Caused by: org.openqa.grid.common.exception.GridException: Error forwarding the new session cannot find : Capabilities [{name=loadGooglePageAndCheckTitle, browserName=safari, platformName=MAC, platform=MAC}]

```

**Comment by diemol** [comment]
I'll take a look into the tests tomorrow, if it works, perhaps you have helped us to fix #232 
Thanks for sending us this PR @jkandasa

**Comment by diemol** [comment]
I'll merge to a different branch so we can run all the tests properly.

**Comment by diemol** [comment]
👍

**Pull request merged**
