### PR TITLE
Updating dependencies for docker and k8s client

### PR DESCRIPTION
**Pull request by diemol**
Updating POM dependencies, previous work to upgrade to 3.13.0 (WIP)

### CODE REVIEW

**Comment by elgalu** [comment]
Just FYI CDP failed with an error un-related to this PR changes:

```
11:15:53 Step 10/50 : RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32 && apt-key update -qqy

11:15:53 ---> Running in 44d2724b535b

11:15:53 Executing: /tmp/tmp.AO2d62UOUe/gpg.1.sh --keyserver

11:16:13 keyserver.ubuntu.com

11:16:13 --recv-keys

11:16:13 3B4FE6ACC0B21F32

11:16:13 gpg: requesting key C0B21F32 from hkp server keyserver.ubuntu.com

11:16:13 gpgkeys: key 3B4FE6ACC0B21F32 can't be retrieved

11:16:13 gpg: no valid OpenPGP data found.

11:16:13 gpg: Total number processed: 0

11:16:13 gpg: keyserver communications error: keyserver helper general error

11:16:13 gpg: keyserver communications error: unknown pubkey algorithm

11:16:13 gpg: keyserver receive failed: unknown pubkey algorithm

11:16:13 The command '/bin/sh -c apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32 && apt-key update -qqy' returned a non-zero code: 2

11:16:13 Step 'Build Zalenium image' finished unsuccessfully.

11:16:13 Closing the connection to the build host

11:16:13 Build step 'Build Zalenium image' failed.
```

**Comment by diemol** [comment]
Thanks @elgalu! The same error showed up in Travis.

**Comment by elgalu** [comment]
The workaround for this gpg problem is to implement a retry on alt mirrors, like this: https://github.com/elgalu/docker-selenium/blob/master/Dockerfile#L42-L61

**Comment by diemol** [comment]
PRs are welcome :)

**Comment by elgalu** [comment]
👍

**Comment by diemol** [comment]
👍

**Comment by diemol** [comment]
@pearj could you please have a look? Just to make sure that the Prometheus and similar stuff is still working for you.

**Comment by diemol** [comment]
👍

**Comment by pearj** [comment]
👍

**Pull request merged**
