### PR TITLE
New dashboard data

### PR DESCRIPTION
**Pull request by robertzett**
This is the pull request for #108 where I've explained in details what the changes are.

### CODE REVIEW

**Comment by diemol** [comment]
Hi @robertzett,
Can you please rebase or first merge from master? It is difficult to review when our commits are present there too.

**Comment by robertzett** [comment]
I am currently rebasing and fixing the codacy and ci warnings.
I know that there are quite some changes that's why I took some time to write the functional explanations in #108 first.

**Comment by robertzett** [comment]
I've finished with rebase work. Also fixed codacy issues and ci build.
Adjusted WaitForVideosTransferred() in zalenium.sh to use dashboardData.json
The "Remove all history" functionallity is still early alpha. I need to solve a timing issue between triggering removal and page refresh at first.

**Comment by diemol** [comment]
Hi @robertzett,

Thanks again for this PR. 

The idea is to cleanup the dashboard on demand, which seems to be achieved. Nevertheless, the PR contains more changes that makes it complicated to review. Conceptually your ideas for the dashboard roadmap make sense and we are keen to include them, but we would need too long to test them properly. 

Having said that, we want to merge this PR since we see that it adds value. But we want to merge it gradually, including feature parts one by one. Therefore, we decide to merge this in a separate branch in the project, and start doing cherry picking to include your contribution step by step.

Generally, we try to have small PRs, so the review and the testing is more simple. That's basically why we will proceed like this.

Again, thanks a lot for your contribution! 🙌

**Comment by diemol** [comment]
👍

**Comment by robertzett** [comment]
Perfectly understandable.
I've been thinking twice before submitting this PR. The main intention has been to change list.html to dashboardData.json and to not leave dead code after the change.

**Comment by sbgreene1307** [comment]
👍

**Pull request merged**
