### PR TITLE
Docker Swarm Implementation

### PR DESCRIPTION
**Pull request by yosserO**
### Description

How to use it:

* Initialize a swarm by running: `docker swarm init`
* Add **at least** one worker to the swarm.
* Deploy a new Stack by running: `docker stack deploy -c <path-to-docker-compose-file> STACK_NAME`.
    - We added an example docker-compose file under _zalenium/docs/docker/docker-compose-swarm.yml_.
    - An attachable  overlay network must be declared in the docker-compose file. This overlay network must be passed to zalenium as the configuration parameter "--swarmOverlayNetwork". In our example we are declaring the overlay network "zalenium". We named our stack "tau". So the corresponding value for the configuration parameter "--swarmOverlayNetwork" is "tau_zalenium".
* We have two different **constraints** for the hub and its nodes:
    - The hub has the constraint `node.role == manager` and will only be deployed on the manager. (Take a look at the example docker-compose file).
    - The nodes have the constraint `node.role==worker`. This constraint is currently hard coded in the _SwarmContainerClient.java_ Class.
* Logs and Videos are currently not supported.
* In order to execute commands on workers we are using this image `datagridsys/skopos-plugin-swarm-exec:latest`. 
* We tested the solution in our own environment but we will be thankful if you test it for your own and give us feedback.
* We update the documention later after positive feedback.
 
### Motivation and Context

Adapt zalenium to be able to run in a docker swarm. 

### How Has This Been Tested?

We tested it manually. For more details please check the **Description**.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tstern** [comment]
During testing our solution, we've discovered a bug which keeps the Thread "AutoStartProxyPoolPoller" forever in the state "WAITING". We do use many docker operations to run Zalenium in a docker swarm. When docker operations run simultaneous the above described error occurs.

This problem is also described in the following issues:

- https://github.com/zalando/zalenium/issues/808
- https://github.com/eclipse-ee4j/jersey/issues/3772

As a solution we run docker operations in synchronized blocks to prevent simultaneous access to docker.
See commit: [#69ae6ab3](https://github.com/zalando/zalenium/pull/907/commits/69ae6ab3ef7c32e06571b196996f1e0352a088ca)

**Comment by diemol** [comment]
Hi @yosserO,

I am sorry I have not had time to review this properly, would it be possible to update this PR with the latest changes from master? I will have time this weekend to review and if everything works out we could release in 1-2 weeks as a beta.

**Comment by yosserO** [comment]
@diemol  any progress on this PR? :)

**Comment by tstern** [comment]
I've merged the master into our implementation branch. On our side everything seems to be ok.

**Comment by diemol** [comment]
I will merge this to a protected branch so we can run all the CI tests, looks good so far.

**Comment by diemol** [comment]
Let's follow up in #982

**Pull request merged**
