### PR TITLE
Reset executed-tests-count if test-count-file is missing

### PR DESCRIPTION
**Pull request by robertzett**
Added an initial Dashboard Test currently only testing executedTests and changed handling of amount_of_run_tests.txt to reset executedTests. This would help if the videos folder is being cleaned (files removed) while Zalenium is still running.

### CODE REVIEW

**Comment by robertzett** [comment]
I'll close this pull request as meanwhile it got out of sync with the head revision.
I also meanwhile have some more ideas in how to connect an html-dashboard to the files it represents. But that would be different suggestion and most likely a different pull request as soon as I have a demo ready.

**Comment by diemol** [comment]
I am actually merging it right now, solving the conflicts and the fix will be included in the next release. Nevertheless, the new Servlet in your branch looks good for a future PR.

**Comment by robertzett** [comment]
Oh! I see. I am also right now merging. I am close to committing my merge.

**Comment by diemol** [comment]
OK, then I'll close this one and wait for the new on. Thanks!

**Pull request closed without merging**
