### PR TITLE
Feature #148 Add add't mount points in node

### PR DESCRIPTION
**Pull request by ReservedDeveloper**
* Added mount points from `/tmp/node/[TARGET_FOLDER_ON_NODE]`
  * Updated documentation

### CODE REVIEW

**Comment by ReservedDeveloper** [comment]
I was not able to run the integration tests locally, but was able to test against a [demo project](https://github.com/geb/geb-example-maven) without issue and see the mount points in question.

That said, this does have a slightly broad approach, so totally understand if you'd rather this be a little narrower in scope (say, perhaps, only able to mount folders within `/home/seluser`)

**Comment by diemol** [comment]
Hi @ReservedDeveloper,

Thanks for this PR!

If I understand correctly, this addresses #148, and it is done like that because the Chrome certs need to be on that specific folder?

If so, perhaps we should take the approach to map all the mount points provided in the `docker run` except the docker socket and the `/home/seluser/videos` folder. Like that the users could mount any folders they want on any location. I am just afraid that we start adding special cases one by one, and it is maybe better to add them all in a flexible way.

Having said that, could you please check the PR again after we release the 1st beta for Kubernetes? (Should happen tomorrow). I expect some merge conflicts after the release for this PR. After that I would be happy to merge it.

**Comment by ReservedDeveloper** [comment]
@diemol That is correct. And I think what you're proposing (minus the protections for `/videos` and the socket) is how it's currently set up. The way it's currently oriented, the node mount simply has the `/tmp/node` stripped from its bind point. So:

* `docker run -v /my/folder:/tmp/node/home/seluser/foobar` will map to each node's `/home/seluser/foobar` folder.
* `docker run -v /my/folder:/tmp/node/tmp/mounted` would mimic the current multi-purpose volume share.
* `docker run -v /my/folder:/tmp/node/etc` would replace the `/etc` folder with the host folder, and perhaps make for some unknown complications, which I attempted to call out in the documentation update, but could be reworded.

**Comment by ReservedDeveloper** [comment]
@diemol Got the latest from master merged in locally. As I'm adding in protections, how would you like mounting a protected point (ex via: `docker run -v /my/local/folder:/tmp/node/home/seluser/videos`) to be handled? 

It could be more permissive, and simply not trim the `/tmp/node` piece. We'd have some inconsistent node mount behavior, but as it's not necessarily a hindrance to operation to mount in the `/tmp` directory, this may be preferred.

Alternatively, could just throw an `IllegalArgumentException` if one of those directories is encountered. Thoughts?

**Comment by diemol** [comment]
To be honest, when I checked the PR the first time I didn't catch the `/tmp/node` part, sorry about that. 

But the only question I have is: why do we need to have that `/tmp/node` prefix? Can't we just leave them as it is since we will filter a couple of ones?

Besides from `/home/seluser/videos` and the docker socket, I would say that we wound't need to filter anything else.

**Comment by ReservedDeveloper** [comment]
I suppose I was thinking of the feature more as 'opt in' than 'opt out'. Help prevent any unexpected issues due to mounting. Or if you were wanting to mount _only_ in the zalenium container, but not the nodes.

If we go that route, I'd likely just skip any conflicting mount points, and add a log stating why it was skipped.

**Comment by diemol** [comment]
@ReservedDeveloper, I think you made a good point. Perhaps having `/tmp/node` as a prefix is a good idea to avoid mounting issues, as you mention. We also "protect" the main Zalenium container in that way I guess.

I think we could go that way, and just document it properly in the current document and in the release (since this is a breaking change for existing users of this feature).

Could you please try to add a unit test for it? I am not sure how easy it is, perhaps we need to refactor something.

**Comment by ReservedDeveloper** [comment]
I'll add that in with the protection updates. I should have the time to put that together tomorrow evening. 

@pearj mentioned an approach for adding the mapping feature to the Kubernetes side that I'm hoping to add in as well, though we could always split that out to a separate ticket.

**Comment by pearj** [comment]
@ReservedDeveloper You shoudl probably keep the kubernetes support for arbitrary mounts a separate ticket I reckon. Especially if you aren't able to test it, and we don't have travis running automatic integration tests for kubernetes yet.

**Comment by diemol** [comment]
Sounds good @ReservedDeveloper, thanks!

 Thanks @pearj for the extra pair of eyes :)

**Comment by ReservedDeveloper** [comment]
Updated to resolve the latest from master, and to add the discussed protections. However, in looking at `DockerContainerClient#createContainer`, building up a unit test may be a little tricky, as you suggested. In particular, the `HostConfig.builder()` and `ContainerConfig.builder()` calls put a wrench in things. I'd considered extracting those out to a wrapper class or something, but that sort of refactoring felt a little out of scope.

**Comment by ReservedDeveloper** [comment]
@diemol not sure how you'd like to proceed on testing. That said, I'd like to take some time this weekend to rebase and clean up the history a touch (as well as resolve my listed email address), so please hold on merging this if you wouldn't mind. Just let me know as far as testing goes!

**Comment by diemol** [comment]
@ReservedDeveloper sounds good. I was going to go over this during the weekend, but sure, when you are ready we can check it again and merge it :)

About the tests, just try but if it ends up to be complicated, then just leave it as it is. I think that we just need to refactor that part of the code to make it more testable.

**Comment by ReservedDeveloper** [comment]
@diemol all good to go. Wasn't able to tackle the unit test stuff, but if you'd like to create a new issue I'd be happy to try and put something together in the coming weeks.

**Comment by diemol** [comment]
Hi @ReservedDeveloper, thanks for putting it all together.

I'll merge it to a branch I created to fix an issue with docker-compose and we'll release that in the next couple of days.

About the unit tests, I need to refactor that code to make it more testable. If you can, keep an eye on it so if you feel like, you can add some unit tests in the near future.

One last thing, I still see the issue with the commits where your user is not really visible, you can fix it whenever you want if you want to be seen in the contributors part :)

**Comment by diemol** [comment]
👍

**Comment by scherniavsky** [comment]
:+1:

**Pull request merged**
