### PR TITLE
Fix issue #672 with RBAC Rolebiding definition

### PR DESCRIPTION
**Pull request by snovikov**
### Description
This would fix issue #672 

### Motivation and Context
Enable to deploy with Helm Chart with RBAC enabled.

### How Has This Been Tested?
Successfully deployed in Kubernetes:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

$ helm install \
  --name zalenium \
  --namespace zalenium \
  --set rbac.create=true \
  --set serviceAccount.create=true \
  --set hub.serviceType=LoadBalancer \
  local/zalenium

$ helm status zalenium
LAST DEPLOYED: Thu Jul 26 11:53:12 2018
NAMESPACE: zalenium
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/Deployment
NAME                   DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
zalenium-zalenium-hub  1        1        1           1          10m

==> v1/Pod(related)
NAME                                    READY  STATUS   RESTARTS  AGE
zalenium-zalenium-hub-694ccfffc9-z8jxg  1/1    Running  0         10m

==> v1/ServiceAccount
NAME      SECRETS  AGE
zalenium  1        10m

==> v1beta1/Role
NAME      AGE
zalenium  10m

==> v1beta1/RoleBinding
NAME      AGE
zalenium  10m

==> v1/Service
NAME      TYPE          CLUSTER-IP     EXTERNAL-IP       PORT(S)         AGE
zalenium  LoadBalancer  100.64.152.39  ab58029ff90b9...  4444:31431/TCP  10m
$ kubectl --namespace=zalenium logs zalenium-zalenium-hub-694ccfffc9-z8jxg
Kubernetes service account found.
Copying files for Dashboard...
Starting Nginx reverse proxy...
Starting Selenium Hub...
...........09:53:16.322 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium build info: version: '3.13.0', revision: 'unknown'
.09:53:16.327 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445
....09:53:17.722 [main] INFO  d.z.e.z.c.k.KubernetesContainerClient - Initialising Kubernetes support
.......09:53:19.825 [main] INFO  d.z.e.z.c.k.KubernetesContainerClient - Kubernetes support initialised.
	Pod name: zalenium-zalenium-hub-694ccfffc9-z8jxg
	app label: zalenium-zalenium-hub
	zalenium service name: zalenium-zalenium-hub
	Selenium Pod Resource Limits: {cpu=Quantity(amount=1000m, format=null, additionalProperties={})}
	Selenium Pod Resource Requests: {memory=Quantity(amount=500Mi, format=null, additionalProperties={}), cpu=Quantity(amount=500m, format=null, additionalProperties={})}
09:53:19.825 [main] INFO  d.z.e.z.c.k.KubernetesContainerClient - About to clean up any left over selenium pods created by Zalenium
09:53:19.913 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Starting poller.
09:53:19.914 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Autostarting container, because 0 is less than min 2
.....09:53:21.418 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockeredSeleniumStarter - Created container [zalenium-zalenium-hub-40000-lw7tc] with dimensions [(1440, 900)] and tz [sun.util.calendar.ZoneInfo[id="UTC",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null]].
09:53:21.419 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Created ContainerCreationStatus [isCreated=true, containerName=zalenium-zalenium-hub-40000-lw7tc, containerId=zalenium-zalenium-hub-40000-lw7tc, nodePort=40000].
09:53:21.426 [main] INFO  d.z.ep.zalenium.aspect.HubAspect - Registering custom Zalenium servlets
09:53:21.516 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockeredSeleniumStarter - Created container [zalenium-zalenium-hub-40000-wrdnh] with dimensions [(1440, 900)] and tz [sun.util.calendar.ZoneInfo[id="UTC",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null]].
09:53:21.516 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Created ContainerCreationStatus [isCreated=true, containerName=zalenium-zalenium-hub-40000-wrdnh, containerId=zalenium-zalenium-hub-40000-wrdnh, nodePort=40000].
..09:53:22.031 [main] INFO  org.openqa.grid.web.Hub - Selenium Grid hub is up and running
09:53:22.031 [main] INFO  org.openqa.grid.web.Hub - Nodes should register to http://100.124.133.6:4445/grid/register/
09:53:22.031 [main] INFO  org.openqa.grid.web.Hub - Clients should connect to http://100.124.133.6:4445/wd/hub
Selenium Hub started!
Sauce Labs not enabled...
Browser Stack not enabled...
TestingBot not enabled...
Zalenium is now ready!
*************************************** Data Processing Agreement ***************************************
By using this software you agree that the following non-PII (non personally identifiable information)
data will be collected, processed and used by Zalando SE for the purpose of improving our test
infrastructure tools. Anonymisation with respect of the IP address means that only the first two octets
of the IP address are collected.

See the complete license at https://github.com/zalando/zalenium/blob/master/LICENSE.md
*************************************** Data Processing Agreement ***************************************
09:54:21.791 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container zalenium-zalenium-hub-40000-lw7tc started after 60371.
09:54:22.522 [Thread-10] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://100.122.238.69:40000
09:54:22.523 [Thread-10] INFO  d.z.e.z.proxy.AutoStartProxySet - Registered a container zalenium-zalenium-hub-40000-lw7tc http://100.122.238.69:40000.
09:54:25.828 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container zalenium-zalenium-hub-40000-wrdnh started after 64312.
09:54:26.015 [Thread-11] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://100.126.235.70:40000
09:54:26.016 [Thread-11] INFO  d.z.e.z.proxy.AutoStartProxySet - Registered a container zalenium-zalenium-hub-40000-wrdnh http://100.126.235.70:40000.
```

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by diemol** [comment]
Thanks @snovikov for sending us a PR! While we check it, would you please rebase your changes to master?

@pearj what do you think?

**Comment by snovikov** [comment]
@diemol the branch was updated

**Comment by diemol** [comment]
Thanks @snovikov 

I just noticed that this file was added by @ecktom, @ecktom do you have any comments on this PR? For me it looks fine, what do you think?

**Comment by ecktom** [comment]
@diemol. Looks good as we are referencing the name and not the fullname in deployment. No clue how this did even work in our setup... ;)

**Comment by diemol** [comment]
Thanks for checking @ecktom!

**Comment by diemol** [comment]
👍

**Comment by diemol** [comment]
Thanks for your contribution @snovikov!

**Pull request merged**
