### PR TITLE
issue #1047 - Dashboard UI is broken when clicking the reset button -…

### PR DESCRIPTION
**Pull request by diemol**
Merging PR 1201
@mookkiah CI running here 👀

### CODE REVIEW

**Comment by diemol** [comment]
@mookkiah seems we cannot run PRs anymore, the cloud integrations are not working because some accounts have expired 🤷 
Sorry.

**Comment by mookkiah** [comment]
@diemol Thank you for creating protected branch to run CI.
I deleted my fork.
Please help me understand what "we cannot run PRs anymore" means.

With respect and curiosity...
Are you or someone going to take care of renewing the integration account for CI to pass?
What is the next step for making this change in release artifact?
What will be the current status & tags of [issue 1047](https://github.com/zalando/zalenium/issues/1047)?

If this change made it to a docker image which I could use,  I can get rid of workarounds introduced to resolve this bug. Please help.

**Comment by diemol** [comment]
We cannot run PRs anymore with all the enabled cloud integrations because some of them expired the user we had to test the integration.

> Are you or someone going to take care of renewing the integration account for CI to pass?

Not really, this project is not maintained anymore and I am happy to reply to questions and help the ones who still use it as much as I can (under my time and workload constraints) 

> What is the next step for making this change in release artifact?

As mentioned above and in the README, this project is not being released anymore. So, even if the PR makes it to the default project branch, we won't be publishing a new docker image. 

> What will be the current status & tags of issue 1047?

I guess they will be left open because we cannot test it completely.

**Comment by mookkiah** [comment]
Thanks for clarity. I understand it.

**Comment by gushev** [comment]
> We cannot run PRs anymore with all the enabled cloud integrations because some of them expired the user we had to test the integration.
> 
> > Are you or someone going to take care of renewing the integration account for CI to pass?
> 
> Not really, this project is not maintained anymore and I am happy to reply to questions and help the ones who still use it as much as I can (under my time and workload constraints)
> 
> > What is the next step for making this change in release artifact?
> 
> As mentioned above and in the README, this project is not being released anymore. So, even if the PR makes it to the default project branch, we won't be publishing a new docker image.
> 
> > What will be the current status & tags of issue 1047?
> 
> I guess they will be left open because we cannot test it completely.

Hi @diemol . I've noticed, that this project is not being released anymore, as you mentioned. Are you working on a similar project at the moment, or are there alternatives to it on the rise? And if there are what would you suggest as one to switch to?

**Comment by diemol** [comment]
@s1mpl3-0n3 yes, https://github.com/SeleniumHQ/docker-selenium is getting most of the features Zalenium already has.

**Pull request closed without merging**
