### PR TITLE
Fix CrossBrowserTesting 

### PR DESCRIPTION
**Pull request by daphnemcrossbrowser**
**Thanks for contributing to Zalenium! Please give us as much information as possible to merge this PR
quickly.**

### Description
Fix CrossBrowsertesting.

### Motivation and Context
Fully enables support for CrossBrowserTesting.

### How Has This Been Tested?
Verified changes locally by building and testing an image with all necessary changes to verify test using --cbtEnabled ran and were properly added to the dashboard.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
Thank you @daphnemcrossbrowser, will merge this soon, test it and release it.

**Comment by diemol** [comment]
Hi @daphnemcrossbrowser,
I was testing it, but it actually does not work. When I start Zalenium with CBT enabled, the proxy used as a connector to CBT dies after 90 seconds since it cannot connect to the CBT url properly. Also, when I try to run a test, it fails right away.

You mention that you were able to run tests and see them in the dashboard, how did you do that? Could you share the steps you followed to achieve that? Thanks!

**Comment by daphnemcrossbrowser** [comment]
Hello @diemol,

I was able to successfully test by 

setting the variables: 
`export CBT_USERNAME="YOUR_USERNAME"`
`export CBT_AUTHKEY="YOUR_AUTHKEY"`
`export CBT_URL= "http://YOUR_USERNAME:YOUR_AUTHKEY@hub.crossbrowsertesting.com:80"`

starting the node with:
`docker run --rm -ti --name zalenium -p 4444:4444 \`
`-e CBT_USERNAME -e CBT_AUTHKEY -e CBT_URL \`
`-v /tmp/videos:/home/seluser/videos \`
`-v /var/run/docker.sock:/var/run/docker.sock \`
`--privileged dosel/zalenium start --cbtEnabled true
`

**Comment by diemol** [comment]
@daphnemcrossbrowser thanks for the stepts, at least I got further :)
Two things:
- Is putting user and key in the url the only way to pass them to CBT? Normally other cloud services allow you to pass them as capabilities. I ask this because the url will be shown in the logs, and maybe some people don't want to see the key in the logs.
- I got this error while running a test:
```
19:36:55.226 [qtp1586151649-18] INFO  o.o.g.w.s.handler.RequestHandler - Error forwarding the new session Error forwarding the request Too many follow-up requests: 21
org.openqa.grid.internal.exception.NewSessionException: Error forwarding the request Too many follow-up requests: 21
	at org.openqa.grid.web.servlet.handler.RequestHandler.forwardNewSessionRequestAndUpdateRegistry(RequestHandler.java:94)
	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:114)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:85)
	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.seleniumhq.jetty9.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at io.prometheus.client.filter.MetricsFilter.doFilter(MetricsFilter.java:170)
	at org.seleniumhq.jetty9.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.seleniumhq.jetty9.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:503)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:364)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:103)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ProtocolException: Too many follow-up requests: 21
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:177)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
	at org.openqa.grid.internal.TestSession.sendRequestToNode(TestSession.java:422)
	at org.openqa.grid.internal.TestSession.forward(TestSession.java:229)
	at org.openqa.grid.web.servlet.handler.RequestHandler.forwardNewSessionRequestAndUpdateRegistry(RequestHandler.java:91)
	... 39 common frames omitted
```
Could it be because my user is diemol@gmail.com, is the `@` causing some issues there?

**Comment by daphnemcrossbrowser** [comment]
@diemol 

The username and authkey can be passed as capabilities instead of adding them to the hub url.
`caps['username'] = "YOUR_USERNAME"`
`caps['password'] = "YOUR_AUTHKEY"`

If setting the username and authkey  in the hub url, the @ symbol in the username should be encoded using %40. If passing as capabilities the @, doesn't have to be encoded.

**Comment by diemol** [comment]
Thanks @daphnemcrossbrowser, by adding the `password` cap, things work right now. We will release right away :)

**Pull request merged**
