### PR TITLE
Use real container name to lookup container ip in k8s

### PR DESCRIPTION
**Pull request by pearj**
Related to #211

### CODE REVIEW

**Comment by pearj** [comment]
👍

**Comment by pearj** [comment]
lol, it was worth a try, approval validation in progress...

**Comment by diemol** [comment]
Thanks! I'll merge this to the branch I am working now, I plan to implement the integration tests with Minikube next week.

**Comment by pearj** [comment]
Thanks! I attempted to write a test on the bus on the way to work to make codecov happy. But it was looking like it would be fiddly to write a useful test. It does seem like an integration test would be the most useful option.

**Pull request merged**
