### PR TITLE
Enabling tests

### PR DESCRIPTION
**Pull request by furkandogan**
@diemol I rebased all commits and sending PR.

### CODE REVIEW

**Comment by diemol** [comment]
@furkandogan I think it is not completely right, this PR has even more commits than the other one. 

Please send a PR with just your changes.

**Comment by furkandogan** [comment]
@diemol  Okey I wiil create new PR and i will send.

**Comment by diemol** [comment]
@furkandogan Just create a PR from this https://github.com/zalando/zalenium/compare/master...furkandogan:master

**Comment by diemol** [comment]
I'll close the two PRs for now.

**Comment by diemol** [comment]
I cannot see the changes anymore, did you delete the branch on your fork?

**Pull request closed without merging**
