### PR TITLE
Run an E2E test in CDP.

### PR DESCRIPTION
**Pull request by bmaher**
### Description
Introduce an end-to-end test to Zalenium, running in Zalando's CI system.

### Motivation and Context
The test consists of:
- A basic Express application
- A basic WDIO test
- A docker-compose consisting of an instance of Zalenium, the application, and the test runner

The idea is that this represents the most basic use-case for Zalenium, and therefore, no change should break this setup.

### How Has This Been Tested?
This has been tested locally using docker-compose to run the test itself.

### Types of changes

- [X] New feature (non-breaking change which adds functionality)

### Checklist:

- [X] My code follows the code style of this project.
- [X] I have read the **CONTRIBUTING** document.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
Thanks @bmaher! Good idea.

Only one thing, what do you think about using this script (or an adaptation) instead of `wait-for-it.sh`?

```
#!/bin/bash
# wait-for-grid.sh

set -e

cmd="$@"

while ! curl -sSL "http://hub:4444/wd/hub/status" 2>&1 \
        | jq -r '.value.ready' 2>&1 | grep "true" >/dev/null; do
    echo 'Waiting for the Grid'
    sleep 1
done

>&2 echo "Selenium Grid is up - executing test"
exec $cmd
``` 

I suggest this since having the port 4444 up and listening is no guarantee that the grid is still able to receive test requests (it might be possible that no nodes have registered yet).

**Comment by bmaher** [comment]
@diemol Sure thing, looks good; I'll switch it out.

**Comment by diemol** [comment]
@bmaher everything looks good to me.

The only question I have is: what do we do when the CDP build fails? I don't have access anymore to the logs and most of the coding nowadays is done during weekends and evenings, so I doubt someone can help right away.

Do you guys have something in mind for those cases?

**Comment by bmaher** [comment]
@diemol Yes I was thinking about that too, I have two ideas:

1. If the build status reports a failure, and running the tests locally show no failure, i.e. a potential CDP issue, then we'd wait until working hours to find a resolution
2. We could make the CDP status non-blocking for a merge, mark the images in some way, and re-verify during working hours

**Comment by diemol** [comment]
I think option 1 sounds fine.

About option 2, I don't think we should mark the CDP build as required to merge. The logs are not accessible publicly and this would go against the Open Source nature of the project, all related things to it must be open and accessible by anyone who wants to contribute.

Besides that, looks great. Thanks for adding those. Extra points would be if we run the same tests in Travis, what do you think @bmaher ?

**Comment by diemol** [comment]
👍

**Comment by elgalu** [comment]
👍

**Pull request merged**
