### PR TITLE
Proxy vnc connections instead of using nodePorts fixes: #323

### PR DESCRIPTION
**Pull request by pearj**
### Description
Replace nodePorts in kubernetes for exposing vnc connections with an nginx proxy with an extra servlet that authenticates each request.

Each proxy request is authenticated against the list of nodes in the registry to ensure that nginx doesn't become an open proxy for the SDN.

### Motivation and Context
A lot of Kubernetes deployments don't allow nodePorts, so another solution which could route of standard http ports was required.

### How Has This Been Tested?
Created a new test case called VncAuthenticationServletTest.  Additionally, I tried modifying the proxy urls to access other resources running in kubernetes and the authentication servlet successfully denied the request.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)\

### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
Thanks @pearj! Let me review this during the weekend.

**Comment by diemol** [comment]
Like we did with other external PRs, I'll merge this to a branch, review and then merge to master.

**Comment by diemol** [comment]
@pearj I didn't find the VncAuthenticationServletTest you mention, maybe you forgot to push it?

**Comment by pearj** [comment]
@diemol whoops you're right, I've added the test in #345

**Pull request merged**
