### PR TITLE
Code changes to enable local development and debugging

### PR DESCRIPTION
**Pull request by diemol**

### CODE REVIEW

**Comment by diemol** [comment]
👍

**Comment by bmaher** [comment]
@diemol  Looks like one of the tests failed:
```bash
09:13:19 [ERROR] LiveNodeServletTest.addedNodesAreRenderedInServlet:77
09:13:19 Expected: a string containing "/vnc/host/machine1/port/40000/?nginx=machine1:40000&view_only=true'"
09:13:19 but: was "<html>
```

Truncated the HTML output, but the page is `Zalenium Live Preview`
There is the following in the HTML, not sure if it's relevant:

```html
09:13:19 <div class='proxy'>
09:13:19 <p class='proxyname'>
09:13:19 DockerSeleniumRemoteProxy unknown version, machine1: Name or service not known
09:13:19 <p class='proxyid'>
09:13:19 id : http://machine1:4444, OS : LINUX, Container Name : zalenium
09:13:19 </p>
```

**Comment by diemol** [comment]
That's strange... How come tests pass in Travis? 
I am not sure how to proceed there :(

**Comment by diemol** [comment]
I don't think it is a flaky test, I don't remember seeing it failing in Travis. 
But yes, maybe triggering the build again helps.

**Comment by bmaher** [comment]
👍

**Pull request merged**
