### PR TITLE
feat(helm): Fixed readme, added missing parameters, enhanced PVC and SA, introduced Ingress and RABC

### PR DESCRIPTION
**Pull request by ecktom**
### Description
This is a backmerge of some adjustments we've made to the helm chart containing:
- Fixed readme
- Added missing parameters
- Enhanced PVC and SA
- Introduced Ingress and RABC

### How Has This Been Tested?
helm lint + helm install in private cluster

### Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by diemol** [comment]
Thanks @ecktom!

Looks good to me, but I'll wait to see if @pearj has any comments.

**Comment by diemol** [comment]
👍

**Comment by pearj** [comment]
Looks like a great improvement.

**Comment by pearj** [comment]
👍

**Pull request merged**
