### PR TITLE
Add documentation about openshift routes

### PR DESCRIPTION
**Pull request by dennisgranath**
Add some instruction regarding routes on documentation for running zalenium in openshift.

### Description
Description on how to create routes in openshift. 

### Motivation and Context
It will be useful for users that want to run zalenium in openshift

### How Has This Been Tested?
Only updates to the documentation.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
Thanks @dennisgranath for helping us improving the docs!

**Comment by diemol** [comment]
👍

**Comment by scherniavsky** [comment]
:+1:

**Comment by dennisgranath** [comment]
No prob @diemol! I'm only glad to be able to help out!

**Pull request merged**
