### PR TITLE
Change Ubuntu Mirror via Args

### PR DESCRIPTION
**Pull request by diemol**

### CODE REVIEW

**Comment by diemol** [comment]
👍

**Comment by peerster** [comment]
👍

**Comment by peerster** [comment]
@pearj How much smaller does the kubernetes version get?

Wondering if maybe it could be worth the trouble of making two docker builds; standard and kubernetes version.

**Comment by pearj** [comment]
@peerster It is only 37 MB less.  It's more that it speeds up build time over here in Australia, so we don't have to download unneeded bits and pieces.

**Comment by pearj** [comment]
I guess you might gain more size decreases if you strip out the Spotify docker library inside the zalenium jar itself. But for that to work, we'd need to make zalenium more modular, so that the kuberentes and docker pieces could be swapped in and out, without compile issues. 

But I don't think we'd gain very much for doing that.

**Pull request merged**
