### PR TITLE
Feature openshift route

### PR DESCRIPTION
**Pull request by torstenwalter**
**Thanks for contributing to Zalenium! Please give us as much information as possible to merge this PR
quickly.**

### Description
I added the possibility to create an OpenShift route. TLS is enabled by default, but it can be disabled.
The hostname is optional as OpenShift creates a default for it based on the route's name and the current namespace.

### Motivation and Context

I want to use this chart to deploy Zalenium to OpenShift. I could use Ingress for that, but using routes feels more natural as I can rely on OpenShift to generate a unique host name.

### How Has This Been Tested?

Tested it locally with Minishift, with and without TLS / hostname.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly. (README is updated)
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed. 

I did not find any helm specifc tests to update.

### CODE REVIEW

**Comment by arnaud-deprez** [comment]
Thanks for your PR @torstenwalter.

From Openshift 3.10, if you create an ingress, it creates a corresponding openshift route.
So I initially think that it didn't make sense to have Openshift route support.

The only facility Openshift provides with its routes is to be able to reuse the same wildcard certificates for all routes. So I guess it make sense to have it for such scenario.

**Comment by torstenwalter** [comment]
@arnaud-deprez You are right! It's basically just to be able to reuse the wildcard certificate. Doest it make sense for that use case?

**Comment by arnaud-deprez** [comment]
Yeah I don't see any objection for it.
However I'm wondering if we should not avoid `tls` by default to have the same behaviour than the usual ingress which is by default to `ingress.tls: false`

**Comment by torstenwalter** [comment]
In my experience it's better to have by default a secure option and to allow users to reduce security if they don't need it.
It's very similar as enabling tbac by default which is documented as helm [best practice](https://helm.sh/docs/chart_best_practices/#rbac-resources-should-be-created-by-default).

As tls certificated are available in most OpenShift installations TLS by default should not cause problems.

**Comment by arnaud-deprez** [comment]
Ok but most default certificate are self-signed by default which might cause some complication on your test side.
If you are using a dev cluster for your test, then most probably your cluster is not exposed to the internet and so you don't really care if it's http or https.

**Comment by torstenwalter** [comment]
I see your point. Although personally I'd like to have everything tls secured even internal communication, but I am fine in chaning this. 

Chart is updated.

**Comment by arnaud-deprez** [comment]
It's ok for me @diemol

**Pull request merged**
